import { test, Page } from '@playwright/test';
import * as path from 'path';
import * as fs from 'fs';
import ExcelJS from 'exceljs';
import 'dotenv/config';

// ============================================================
// CONFIGURATION
// ============================================================

const SETTINGS_FILE = path.resolve(__dirname, '..', '.test-settings.json');
let savedUrl = '';
try {
  const s = JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf-8'));
  savedUrl = s.d365Url || '';
} catch { /* use fallback */ }

const D365_URL = savedUrl || process.env.D365_URL || 'https://REPLACE_WITH_YOUR_ORG.crm.dynamics.com';
const RESPONSE_TIMEOUT = parseInt(process.env.COPILOT_RESPONSE_TIMEOUT || '60', 10) * 1000;
const SIMILARITY_THRESHOLD = parseFloat(process.env.SIMILARITY_THRESHOLD || '0.6');

const INPUT_XLSX = path.resolve(__dirname, '..', 'Prompts and Responses.xlsx');
const RESULTS_DIR = path.resolve(__dirname, '..', 'test-results', 'parallel');

// ============================================================
// PROMPT DATA — read synchronously so tests can be generated
// ============================================================

interface PromptRow {
  prompt: string;
  expectedResponse: string;
  referencedDocs: string;
}

function readPromptsSync(): PromptRow[] {
  // The prompts-cache.json is generated by global-setup-parallel.ts.
  // If it doesn't exist yet, generate it via the cache-prompts helper.
  const cacheFile = path.resolve(__dirname, '..', 'test-results', 'prompts-cache.json');
  if (!fs.existsSync(cacheFile)) {
    const { execSync } = require('child_process');
    const script = path.resolve(__dirname, '..', 'cache-prompts.js');
    execSync(`node "${script}"`, { stdio: 'inherit' });
  }
  if (fs.existsSync(cacheFile)) {
    return JSON.parse(fs.readFileSync(cacheFile, 'utf-8'));
  }
  return [];
}

const prompts = readPromptsSync();

// ============================================================
// HELPERS
// ============================================================

function similarity(a: string, b: string): number {
  const tokenize = (s: string) => {
    const tokens = s.toLowerCase().replace(/[^a-z0-9\s]/g, '').split(/\s+/).filter(Boolean);
    return new Set(tokens);
  };
  const setA = tokenize(a);
  const setB = tokenize(b);
  if (setA.size === 0 || setB.size === 0) return 0;
  let intersection = 0;
  for (const word of setA) {
    if (setB.has(word)) intersection++;
  }
  return intersection / Math.max(setA.size, setB.size);
}

interface TestResult {
  index: number;
  prompt: string;
  expectedResponse: string;
  actualResponse: string;
  similarity: number;
  pass: boolean;
  referencedDocs: string;
}

// ============================================================
// D365 COPILOT INTERACTION
// ============================================================

const COPILOT_CONTAINER_SEL =
  '[data-id="MscrmControls.CSIntelligence.AICopilotControl_container"]';

async function findCopilotInput(page: Page): Promise<ReturnType<Page['locator']>> {
  const selectors = [
    `${COPILOT_CONTAINER_SEL} [role="textbox"][aria-label="Describe what you need"]`,
    `${COPILOT_CONTAINER_SEL} [role="textbox"]`,
    `${COPILOT_CONTAINER_SEL} [class*="EditorInput"] [role="textbox"]`,
    `${COPILOT_CONTAINER_SEL} textarea`,
    `${COPILOT_CONTAINER_SEL} input[type="text"]`,
    `${COPILOT_CONTAINER_SEL} [contenteditable="true"]`,
  ];

  for (const sel of selectors) {
    const loc = page.locator(sel).first();
    if (await loc.isVisible({ timeout: 2000 }).catch(() => false)) {
      return loc;
    }
  }

  throw new Error('Could not find the Copilot chat input.');
}

async function openCopilotPanel(page: Page) {
  const container = page.locator(COPILOT_CONTAINER_SEL);
  if (await container.isVisible({ timeout: 3000 }).catch(() => false)) return;

  const tabButton = page.locator(
    '[data-id*="sidepane-tab-button-AppSidePane_MscrmControls.CSIntelligence.AICopilotControl"] button'
  ).first();
  if (await tabButton.isVisible({ timeout: 5000 }).catch(() => false)) {
    await tabButton.click();
    await page.waitForTimeout(2000);
    return;
  }

  const copilotBtn = page.locator('button[aria-label="Copilot"]').first();
  if (await copilotBtn.isVisible({ timeout: 3000 }).catch(() => false)) {
    await copilotBtn.click();
    await page.waitForTimeout(2000);
  }
}

async function sendPromptAndGetResponse(page: Page, prompt: string): Promise<string> {
  const container = page.locator(COPILOT_CONTAINER_SEL);
  const textBefore = await container.innerText().catch(() => '');

  const input = await findCopilotInput(page);
  await input.click();

  try {
    await input.fill(prompt);
  } catch {
    await input.pressSequentially(prompt, { delay: 20 });
  }

  const sendBtn = page.locator(`${COPILOT_CONTAINER_SEL} button[aria-label="Send"]`).first();
  if (await sendBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
    await sendBtn.click();
  } else {
    await input.press('Enter');
  }

  // Wait for response
  const responseDeadline = Date.now() + RESPONSE_TIMEOUT;
  let currentText = textBefore;
  while (currentText === textBefore && Date.now() < responseDeadline) {
    await page.waitForTimeout(1000);
    currentText = await container.innerText().catch(() => '');
  }

  if (currentText === textBefore) {
    return 'ERROR: No response appeared within timeout.';
  }

  // Wait for stability
  let lastText = currentText;
  let stableCount = 0;
  const stabilityDeadline = Date.now() + 90_000;
  while (stableCount < 3 && Date.now() < stabilityDeadline) {
    await page.waitForTimeout(1000);
    currentText = await container.innerText().catch(() => '');
    if (currentText === lastText) {
      stableCount++;
    } else {
      stableCount = 0;
      lastText = currentText;
    }
  }

  const fullText = currentText;
  const promptIdx = fullText.lastIndexOf(prompt);
  if (promptIdx !== -1) {
    const afterPrompt = fullText.slice(promptIdx + prompt.length).trim();
    if (afterPrompt.length > 0) return afterPrompt;
  }

  if (fullText.length > textBefore.length) {
    return fullText.slice(textBefore.length).trim();
  }

  return fullText.trim();
}

async function dismissPopups(page: Page) {
  const selectors = [
    '[role="dialog"] button[aria-label="Dismiss"]',
    '[role="dialog"] button[aria-label="Close"]',
    'button[aria-label="Dismiss"]',
    'button[aria-label="Close"]',
    'button:has-text("Got it")',
    'button:has-text("Skip")',
  ];

  for (const sel of selectors) {
    try {
      const btn = page.locator(sel).first();
      if (await btn.isVisible({ timeout: 300 }).catch(() => false)) {
        await btn.click();
        await page.waitForTimeout(500);
      }
    } catch { /* ignore */ }
  }
}

async function waitForD365Ready(page: Page) {
  await page.locator('[data-id="appBreadCrumb"]')
    .waitFor({ state: 'visible', timeout: 120_000 });
  await page.locator(COPILOT_CONTAINER_SEL)
    .waitFor({ state: 'attached', timeout: 60_000 });
  await page.locator(`${COPILOT_CONTAINER_SEL} [role="textbox"]`)
    .waitFor({ state: 'visible', timeout: 60_000 });
}

/**
 * Full D365 setup for a single worker: navigate, wait, dismiss popups.
 * Each parallel worker calls this independently.
 */
async function setupD365(page: Page) {
  page.on('dialog', async (dialog) => {
    await dialog.dismiss();
  });

  await page.goto(D365_URL, { waitUntil: 'load', timeout: 120_000 });
  await waitForD365Ready(page);
  await openCopilotPanel(page);
  await dismissPopups(page);
  await page.waitForTimeout(2000);
  await dismissPopups(page);
}

/**
 * Save a single test result as JSON for later merging.
 */
function saveResult(result: TestResult) {
  fs.mkdirSync(RESULTS_DIR, { recursive: true });
  const file = path.join(RESULTS_DIR, `result-${String(result.index).padStart(3, '0')}.json`);
  fs.writeFileSync(file, JSON.stringify(result, null, 2));
}

// ============================================================
// PARALLEL TESTS — one test per prompt
// ============================================================

test.describe('D365 Copilot parallel tests', () => {
  for (let i = 0; i < prompts.length; i++) {
    const promptRow = prompts[i];
    const label = promptRow.prompt.slice(0, 60) + (promptRow.prompt.length > 60 ? '...' : '');

    test(`Prompt ${i + 1}: ${label}`, async ({ page }) => {
      // Each worker navigates to D365 independently
      await setupD365(page);

      let actualResponse = '';
      let sim = 0;
      let pass = false;

      try {
        actualResponse = await sendPromptAndGetResponse(page, promptRow.prompt);
        sim = similarity(promptRow.expectedResponse, actualResponse);
        pass = sim >= SIMILARITY_THRESHOLD;
        console.log(`  → Similarity: ${(sim * 100).toFixed(1)}% — ${pass ? 'PASS' : 'FAIL'}`);
      } catch (err: any) {
        actualResponse = `ERROR: ${err.message}`;
        console.error(`  → Error: ${err.message}`);
      }

      const result: TestResult = {
        index: i + 1,
        prompt: promptRow.prompt,
        expectedResponse: promptRow.expectedResponse,
        actualResponse,
        similarity: sim,
        pass,
        referencedDocs: promptRow.referencedDocs,
      };

      // Save result for merging
      saveResult(result);
    });
  }
});
